#Toml configs

server_port = ":8086"
log_path = "logfiles/custLog"
ginlog_path = "logfiles/ginLog"

[database]
db_name = "agserv"
db_password = "162747"
db_user = "postgres"
db_type = "postgres"
#db_host = "localhost"
db_host = "192.168.115.115"
db_MaxOpen = 30
db_MaxIdle = 10
